Cart/urls.py
from django.urls import path 
from . import views

app_name='Cart'

urlpatterns = [
    path('add_user_order/',views.add_user_order,name='add_user_order'),
    path('cart/',views.user_open_order,name='user_open_order'),
    path('remove/<int:id>/',views.remover_order_detail,name='remove'),
    path('removecookie/<int:id>/',views.remove_from_cookie,name='removeck'),
    path('paid/',views.order_payed,name='paid'),
    path('address/',views.addressView,name='address'),
    path('update_In/',views.update_In_open_order,name='update_In_open_order'),
]

account/urls.py
from urllib import request
from django.urls import path
from . import views 

app_name='account'

urlpatterns = [
    path('register/',views.registerView,name='registerView'),
    path('login/',views.Login,name='login'),
    path('sendsms1/',views.send_sms_test,name='send'),
    path('VerifyChecked/',views.VerifyChecked,name='verify'),
    path('complateprofile/',views.ComplateProfileView,name='comp'),
    path('complateform/',views.ComplateProfile,name='complate'),
    path('resetpassword/',views.respass,name='resetpasswordsms'),
    path('sendsms2/',views.SendSmsReset,name='send2'),
    path('Change/',views.VerifyChecked2,name='changepass'),
    path('Changepassword2/',views.ResetProfile,name='resetprofile'),
    path('info/',views.infoUser,name='info'),
    path('logout/',views.LogOut,name='logout'),

]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('',include('product.urls')),
    path('',include('account.urls')),
    path('',include('ckeditor_uploader.urls')),
    path('',include('Cart.urls')),
    path('',include('payment.urls'))
]


from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name='home'

urlpatterns = [
    path('',views.home,name='home'),
    path('header/',views.header,name='header'),
    path('footer/',views.footer,name='footer')
]

home/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField

class Tabligh(models.Model):
    text = models.CharField(max_length=400)
    link = models.URLField(blank=True)
    def __str__(self):
        return self.text

class TagNav(models.Model):
    name = models.CharField(max_length=100,verbose_name='تگ ها')    
    def __str__(self):
        return self.name

class TagNewPage(models.Model):
    name = models.CharField(max_length=100,verbose_name='تگ ها')    
    def __str__(self):
        return self.name


class SiteSetting(models.Model):
    name = models.CharField(max_length=50,verbose_name='اسم سایت')
    logo = models.FileField(null=True,verbose_name='لوگو')
    alt = models.CharField(max_length=100,null=True,verbose_name='توضیحات لوگو')
    favicon = models.FileField(null=True,verbose_name='آیکون')
    alt2 = models.CharField(max_length=100,null=True,verbose_name='توضیحات icon')
    text = models.CharField(max_length=500,null=True,verbose_name='متن')
    text_vasat_nav = models.CharField(max_length=100,null=True,verbose_name='متن وسط نوبار') 
    image_bg = models.ImageField(null=True,verbose_name='عکس بک گراند صفحات داخلی')
    alt_bg = models.CharField(max_length=100,null=True,verbose_name='توضیح عکس بک گراند')
    telephon = models.CharField(max_length=30,null=True,verbose_name='تلفن')
    email= models.EmailField(max_length=100,null=True,verbose_name='ایمیل')
    address = models.CharField(max_length=200,null=True,verbose_name='ادرس')
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=False,verbose_name='نمایش داده شود؟')

    def __str__(self):
        return self.name


class NavAsli(models.Model):
    parent = models.ForeignKey('self',on_delete=models.SET_NULL,blank=True,null=True,default=None)
    name = models.CharField(max_length=50,verbose_name='نام')
    link = models.CharField(max_length=100,blank=True,null=True,verbose_name='ادرس صفحه')
    body = RichTextUploadingField(null=True,blank=True,verbose_name='بدنه')
    url_title = models.CharField(null=True,blank=True,max_length=300,verbose_name='نام صفحه')
    text = models.TextField(null=True,blank=True,verbose_name='متن')
    tag = models.ManyToManyField(TagNav,blank=True,verbose_name='تگ ها')

    class Meta:
        verbose_name='نوبار'
        verbose_name_plural='نوبارها'
        ordering = ['name']

    def __str__(self):
        return self.name

class Slider(models.Model):
    DIR = (
        ('right','right'),
        ('center','center'),
        ('left','left')
    )
    text_bold = models.CharField(max_length=300,verbose_name='متن بولد')
    text_simple = models.CharField(max_length=300,null=True,verbose_name='متن ساده')
    text_dir = models.CharField(max_length=20,choices=DIR,verbose_name='پوزیشن متن')
    image = models.ImageField(verbose_name='عکس سلایدر')
    alt = models.CharField(max_length=100,verbose_name='توضیح عکس')
    name_button = models.CharField(max_length=100,verbose_name='متن دکمه')
    link = models.CharField(max_length=100,blank=True,null=True,verbose_name='ادرس صفحه')
    body = RichTextUploadingField(null=True,blank=True,verbose_name='بدنه')
    url_title = models.CharField(null=True,blank=True,max_length=300,verbose_name='نام صفحه')
    text = models.TextField(null=True,blank=True,verbose_name='متن')
    tag = models.ManyToManyField(TagNewPage,blank=True,verbose_name='تگ ها')
    
    def __str__(self):
        return self.name_button + " | " + self.link


class FooterAsli(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name

class FooterZir(models.Model):
    footer = models.ForeignKey(FooterAsli,on_delete=models.PROTECT)
    name = models.CharField(max_length=50,verbose_name='نام')
    link = models.CharField(max_length=100,null=True,verbose_name='لینک صفحه')
    body = RichTextUploadingField(null=True,blank=True,verbose_name='بدنه')
    url_title = models.CharField(null=True,blank=True,max_length=300,verbose_name='نام صفحه')
    text = models.TextField(null=True,blank=True,verbose_name='متن')
    tag = models.ManyToManyField(TagNav,blank=True,verbose_name='تگ ها')
    def __str__(self):
        return  str(self.footer.name) + " | " +  self.name + " | " + self.link

templates/address.html
{% extends 'base.html' %}
{% load static %}

{% block body %}

<div id="page-content">
    <!--Page Title-->
    <div class="page section-header text-center">
        <div class="page-title">
            <div class="wrapper"><h1 class="page-width">سبد خرید شما</h1></div>
          </div>
    </div>
    <!--End Page Title-->
    
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-12 col-md-8 col-lg-8 main-col">
                <form action="{% url 'account:info' %}" method="post">
                {% csrf_token %}
                   
                    <div id="shipping-calculator" class="mb-4">
                    <h5 class="small--text-center">تخمین های حمل و نقل را دریافت کنید</h5>
                    <div class="row">
                        <div class="col-12 col-sm-12 col-md-4">
                            <div class="form-group">
                                <label for="address_country">استان</label>
                                <input type="text" name="province" value="{{prof.province}}">
                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-4">
                            <div class="form-group">
                                <label>شهر</label>
                                <input type="text" name="city" value="{{prof.city}}">
                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-4">
                            <div class="form-group">
                                <label for="address_zip">کد پستی</label>
                                  <input type="text" id="address_zip" name="code_posty" value="{{prof.code_posty}}">
                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-4">
                            <div class="form-group">
                                <label for="address_zip2">نام تحویل گیرنده</label>
                                  <input type="text" id="address_zip2" name="receiver_name" value="{{prof.receiver_name}}">
                            </div>
                        </div>
                        <div class="col-12 col-sm-12 col-md-4">
                            <div class="form-group">
                                <label for="address_zip">کدملی</label>
                                  <input type="text" id="address_zip" name="code_meli" value="{{prof.code_meli}}">
                            </div>
                        </div>
                        <div class="col-12 col-sm-12">
                            <div class="form-group">
                                <label for="address_zip">آدرس دقیق</label>
                                <textarea name="address" cols="40" rows="10" required="" id="id_address">{{prof.address}}</textarea>
                            </div>
                        </div>
                        <div class="currencymsg">همه سفارشات را به صورت تومان پردازش می کنیم.</div>
                        <hr> 
                        <div class="col-12 col-sm-12 col-md-12 actionRow text-center">
                              <div><input name='btn1' type="submit" class="btn btn--secondary get-rates" value="محاسبه هزینه حمل و نقل"></div>
                          </div>
                    </div>
                </div>
                </form>                   
               </div>
            <div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
                {% comment %} 
                <div class="cart-note">
                    <div class="solid-border">
                        <h5><label for="CartSpecialInstructions" class="cart-note__label small--text-center">یادداشت خود را به سفارش خود اضافه کنید</label></h5>
                        <textarea name="note" id="CartSpecialInstructions" class="cart-note__input"></textarea>
                    </div>
                </div> 
                {% endcomment %}
                <div class="solid-border">
                  <div class="row">
                      <span class="col-12 col-sm-6 cart__subtotal-title"><strong>مجموع</strong></span>
                      <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-left"><span class="money">{{total}}تومان</span></span>
                    </div>
                  <div class="cart__shipping">حمل و نقل و مالیات در پرداخت محاسبه شده است</div>
                  <p class="cart_tearm">
                    <label>
                      <input type="checkbox" name="tearm" id="cartTearm" class="checkbox" value="tearm" required="">
                        با شرایط و ضوابط موافقم
                    </label>
                  </p>
                  <input type="submit" name="checkout" id="cartCheckout" class="btn btn--small-wide checkout" value="پرداخت" disabled="disabled">
                </div>
            </div>
        </div>
    </div>
    
</div>
{% endblock %}

templates/footer.html
  <!--Footer-->
  <footer id="footer" class="footer-2">
    <div class="newsletter-section">
        <div class="container">
            <div class="row">
                <div class="col-12 col-sm-12 col-md-12 col-lg-7 w-100 d-flex justify-content-start align-items-center">
                    <div class="display-table">
                        <div class="display-table-cell footer-newsletter">
                            <div class="section-header text-center">
                                <label class="h2"><span>ثبت نام برای  </span>خبر نامه</label>
                            </div>
                            <form action="#" method="post">
                                <div class="input-group">
                                    <input disabled type="email" class="input-group__field newsletter__input" name="EMAIL"
                                           value="" placeholder="ایمیل" required="">
                                    <span class="input-group__btn">
                                            <button disabled  type="submit" class="btn newsletter__submit" name="commit" id="Subscribe">
                                                <span class="newsletter__submit-text--large">اشتراک</span>
                                            </button>
                                    </span>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-sm-12 col-md-12 col-lg-5 d-flex justify-content-end align-items-center">
                    <div class="footer-social">
                        <ul class="list--inline site-footer__social-icons social-icons">

                            <li><a class="social-icons__link" href="mailto:{{sitesetting.email}}" target="_blank"
                                   title="ما را در توئیتر دنبال کنید"><i class="icon icon-email"></i> <span
                                   class="icon__fallback-text">Email</span>
                            </a></li>
                            <li><a class="social-icons__link" href="Tel:{{sitesetting.telephon}}" target="_blank"
                                title="ما را در توئیتر دنبال کنید"><i class="icon anm anm-phone-s"></i> <span
                                class="icon__fallback-text">Phone</span>
                            </a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="site-footer">
        <div class="container">
            <!--Footer Links-->
            <div class="footer-top text-right">
                <div class="row">
                    {% for footerasli in footeraslis %}
                    <div class="col-12 col-sm-12 col-md-3 col-lg-3 footer-links">
                        <h4 class="h4">{{footerasli.name}}</h4>
                        <ul>
                            {% for footer in footerasli.footerzir_set.all %}
                            <li><a href="{{footer.link}}">{{footer.name}}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endfor %}

                    <div class="col-12 col-sm-12 col-md-3 col-lg-3 contact-box">
                        <h4 class="h4">ارتباط با ما</h4>
                        <ul class="addressFooter">
                            <li><i class="icon anm anm-map-marker-al"></i>
                                <p>{{sitesetting.address}}</p>
                            </li>
                            <li class="phone"><i class="icon anm anm-phone-s"></i>
                                <p dir="ltr" ><a href="Tel:{{sitesetting.telephon}}">{{sitesetting.telephon}}</a></p>
                            </li>
                            <li class="email"><i class="icon anm anm-envelope-l"></i>
                                <p style="font-family: IRANSans;"><a href="mailto:{{sitesetting.email}}">{{sitesetting.email}}</a></p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--End Footer Links-->
            <hr>
            <div class="footer-bottom">
                <div class="row">
                    <!--Footer Copyright-->
                    <div class="col-12 col-sm-12 col-md-6 col-lg-12 order-1 order-md-0 order-lg-0 order-sm-1 copyright text-center">
                        <p>  طراحی و توسعه در تیم<a href="https://sammotlagh.com/" target="blank">  پزشک کسب و کار  </a></p>
                    </div>
                    <!--End Footer Copyright-->
                </div>
            </div>
        </div>
    </div>
</footer>
<!--End Footer-->
<!--Scoll Top-->
<span id="site-scroll"><i class="icon anm anm-angle-up-r"></i></span>
<!--End Scoll Top-->

templates/header.html
{% load static %}

<!--Promotion Bar-->
<div class="notification-bar mobilehide">
    <a href="{{tabligh.link}}" class="notification-bar__message">{{tabligh.text}}</a>
    <span class="close-announcement">×</span>
</div>
<!--End Promotion Bar-->

<!--Search Form Drawer-->
<div class="search">
    <div class="search__form">
        <form class="search-bar__form" action="#">
            <button class="go-btn search__button" type="submit"><i class="icon anm anm-search-l"></i></button>
            <input class="search__input" type="search" name="q" value="" placeholder="جست و جو در فروشگاه..."
                   aria-label="Search" autocomplete="off">
        </form>
        <button type="button" class="search-trigger close-btn"><i class="anm anm-times-l"></i></button>
    </div>
</div>
<!--End Search Form Drawer-->

<!--Top Header-->
<div class="top-header">

    <div class="container-fluid">
        <div class="row">
            <div class="col-10 col-sm-8 col-md-5 col-lg-4 text-right">
                <div class="language-dropdown">
                    <span class="language-dd">فارسی</span>
                    <ul id="language">
                        <li class="">English<br>coming soon</li>
                        <li class="">Français<br>Bientôt</li>
                    </ul>
                </div>
                <p class="phone-no" dir="ltr"><a href="Tel:{{sitesetting.telephon}}" > {{sitesetting.telephon}}</a> <i class="anm anm-phone-s"></i></p>
            </div>
            <div class="col-sm-4 col-md-4 col-lg-4 d-none d-lg-none d-md-block d-lg-block center-title">
                <div class="text-center">
                    <p class="top-header_middle-text"> {{sitesetting.text_vasat_nav}}</p>
                </div>
            </div>
            <div class="col-2 col-sm-4 col-md-3 col-lg-4 text-left">
                <span class="user-menu d-block d-lg-none"><i class="anm anm-user-al" aria-hidden="true"></i></span>
                <ul class="customer-links list-inline">
                    {% if request.user.is_authenticated %}
                    <li><a href="/logout/">خروج از حساب</a></li>
                    {% else %}
                    
                    <li><a href="/login/">ورود</a></li>
                    <li><a href="/register/">ایجاد حساب کاربری</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<!--End Top Header-->

<!--Header-->
<div class="header-wrap animated d-flex border-bottom">
    <div class="container-fluid">
        <div class="row align-items-center">
            <!--Desktop Logo-->
            {{request.user}}
            <div class="logo col-md-2 col-lg-2 d-none d-lg-block text-right">
                <a href="{% url 'home:home' %}">
                    <img src="{{sitesetting.logo.url}}" alt="{{sitesetting.alt}}" title="{{sitesetting.name}}">
                </a>
            </div>
            <!--End Desktop Logo-->
            <div class="col-2 col-sm-3 col-md-3 col-lg-8">
                <div class="d-block d-lg-none">
                    <button type="button" class="btn--link site-header__menu js-mobile-nav-toggle mobile-nav--open">
                        <i class="icon anm anm-times-l"></i>
                        <i class="anm anm-bars-r"></i>
                    </button>
                </div>
                <!--Desktop Menu-->
                <nav class="grid__item" id="AccessibleNav">
                    <!-- for mobile -->
                    <ul id="siteNav" class="site-nav medium center hidearrow">
                        {% for nav in navaslis %}
                        {% if nav.parent == None %}
                        <li class="lvl1 parent dropdown"><a href="{{nav.link}}">{{nav.name}}<i
                                class="anm anm-angle-down-l"></i></a>
                            {% if nav.navasli_set.all %}
                                {% include 'looped_nav.html' %}
                            {% endif %}
                        </li>
                        {% endif %}
                        {% endfor %}
                    </ul>
                </nav>
                <!--End Desktop Menu-->
            </div>
            <!--Mobile Logo-->
            <div class="col-6 col-sm-6 col-md-6 col-lg-2 d-block d-lg-none mobile-logo">
                <div class="logo">
                    <a href="index.html">
                        <img src="{% static 'assets/images/logo.svg' %}" alt="Belle Multipurpose Html Template"
                             title="قالب چند منظوره فروشگاهی Belle"/>
                    </a>
                </div>
            </div>
            <!--Mobile Logo-->
            <div class="col-4 col-sm-3 col-md-3 col-lg-2">
                <div class="site-cart">
                    <a href="{% url 'Cart:user_open_order' %}" class="site-header__cart" title="سبد خرید">
                        <i class="icon anm anm-bag-l"></i>
                    </a>
                    
                </div>
                <div class="site-header__search">
                    {% comment %} <button type="button" class="search-trigger"><i class="icon anm anm-search-l"></i></button> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Header-->

<div class="mobile-nav-wrapper" role="navigation">
    <div class="closemobileMenu"><i class="icon anm anm-times-l pull-right"></i> بستن</div>
    <ul id="MobileNav" class="mobile-nav">
        {% for nav in navaslis %}
        {% if nav.parent == None %}
            <li class="lvl1 parent megamenu"><a href="{{nav.link}}">{{nav.name}}<i class="anm anm-plus-l"></i></a>
            {% comment %} <li class="lvl1 parent dropdown"><a href="{{nav.link}}">{{nav.name}}<i
                    class="anm anm-angle-down-l"></i></a> {% endcomment %}
                {% if nav.navasli_set.all %}
                    {% include 'looped_nav.html' %}
                {% endif %}
            </li>
        {% endif %}
        {% endfor %}
    </ul>
</div>

templates/looped_nav.html
<ul class="dropdown">
    {% for nav in nav.navasli_set.all %}
    <li><a href="{{nav.link}}" class="site-nav">{{nav.name}}{% if nav.navasli_set.all %}<i
            class="anm anm-angle-left-l"></i>{% endif %}</a>
        {% if nav.navasli_set.all %}
            {% include 'looped_nav.html' %}
        {% endif %}
    </li>
    {% endfor %}
</ul>